Repository Anjaliavv51/Matrubodhah, pull requests merged in 2025-01, with the labels that each got.

#29 Footer Added
  counting.html
  countingpage.html
  footercss.css
  index.html
Labels: SWOC, INTERMEDIATE

#48 Added a feedback page
  counting.html
  countingpage.html
  feedback.css
  feedback.html
  index.html
  styles.css
Labels: SWOC, ADVANCED

#74 COUNTING PAGE navbar now shows login button as shows in all pages
  countingpage.html
  feedback.html
Labels: good first issue, SWOC, BEGINNER

#77 Fix: Redirecting Links for About Section on Login, Sign-Up, and Counting Pages issue 72
  countingpage.html
  feedback.html
  login.html
  signup.html
Labels: SWOC, BEGINNER

#67 Fixed page empty on load #30
  scrollscript.js
Labels: good first issue, SWOC, BEGINNER

#130 ADD CONTRIBUTOR PAGE AND CONNECT TO OTHER PAGES
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  counting.html
  countingpage.html
  feedback.html
  index.html
  login.html
  signup.html
Labels: SWOC, ADVANCED

#124 Add hover effect on social media icons
  footercss.css
Labels: SWOC, INTERMEDIATE

#138 Fixed Issue in Feedback
  feedback.html
Labels: good first issue, SWOC, INTERMEDIATE

#146 Backend Initialization
  .gitignore
  login.html
  server/.gitignore
  server/api/index.js
  server/app.js
  server/controllers/user.controller.js
  server/db.js
  server/models/user.model.js
  server/package-lock.json
  server/package.json
  server/routes/user.routes.js
  signup.html
Labels: good first issue, SWOC, ADVANCED

#168 Upadte the fooder with animation
  footercss.css
  index.html
Labels: enhancement, good first issue, SWOC, INTERMEDIATE

#180 🔧✨ Fixed UI/UX: Improved Scroll Button for Better User Experience
  countingpage.html
  index.html
Labels: enhancement, good first issue, SWOC, ADVANCED

#187 PR-✨[feature Request]: create Activities Page
  activities.css
  activities.html
  counting.html
  countingpage.html
  faq.html
  feedback.html
  index.html
  login.html
  terms.html
Labels: good first issue, SWOC, ADVANCED

#191 Add Star on GitHub button
  counting.html
  countingpage.html
  faq.html
  feedback.css
  feedback.html
  footercss.css
  index.html
  pages/about-page.css
  pages/about-page.html
Labels: enhancement, SWOC, ADVANCED

#186 Add contact us page
  contact.css
  contact.html
  counting.html
  countingpage.html
  faq.html
  feedback.html
  index.html
  login.html
  terms.html
Labels: enhancement, SWOC, INTERMEDIATE, :heavy_plus_sign: Points

#197 Feedback Form Alignment Fixed
  feedback.css
  styles.css
Labels: SWOC, BEGINNER, :heavy_plus_sign: Points

#206 🌟 Added Scroll Button to the Activities Page 🚀
  activities.html
Labels: SWOC

#210 feat: add User profile controllers
  server/app.js
  server/controllers/profile.controller.js
  server/package-lock.json
  server/package.json
  server/routes/profile.routes.js
Labels: SWOC, ADVANCED, Backend

#213 Add Carousel feature for Roadmap Section
  aryabhatta.png
  diya.jpg
  index.html
  mythology.png
  rangoli.jpg
  roadmap.js
  sanskrit.png
  scontentcss.css
  shiv.png
  yoga.png
Labels: enhancement, good first issue, SWOC, ADVANCED

#227 Added profile page
  edit-profile.html
  profile.html
  server/controllers/profile.controller.js
  user-avatar.png
Labels: SWOC, ADVANCED, :heavy_plus_sign: Points, Backend
