Repository Anjaliavv51/Matrubodhah, pull requests merged in 2025-02, with the labels that each got.

#229 Added Navbar Animation
  Scroll.js
  activities.html
  contact.html
  countingpage.html
  faq.html
  feedback.html
  index.html
  index.js
  login.html
  scrollscript.js
Labels: SWOC, ADVANCED, :heavy_plus_sign: Points

#256 fix: View-Service page in Home
  .vscode/settings.json
  View-Service.html
  index.html
Labels: SWOC, ADVANCED

#274 fix: Fixed Navbar on about us page
  pages/about-page.html
Labels: enhancement, SWOC, ADVANCED, :heavy_plus_sign: Points

#286 Added VedicFacts :#64
  108.jpg
  Counting/108.jpg
  Counting/EIGHT.jpg
  Counting/FIVE.jpg
  Counting/FOUR.jpg
  Counting/NINE.jpg
  Counting/ONE.jpg
  Counting/SEVEN.jpg
  Counting/SIX.jpg
  Counting/TEN.jpg
  Counting/THREE.jpg
  Counting/TWO.jpg
  Counting/ZERO.jpg
  FOUR.png
  Vedic_Facts.html
  Vedic_Facts/F1.jpg
  Vedic_Facts/F2.jpg
  Vedic_Facts/F3.jpg
  Vedic_Facts/F4.jpg
  Vedic_Facts/F5.jpg
  Vedic_Facts/F6.jpg
  Vedic_Facts/F7.jpg
  Vedic_Facts/F8.jpg
  ZERO.jpg
  activities.html
  contact.html
  countingpage.html
  faq.html
  feedback.html
  index.html
  login.html
  package-lock.json
  profile.html
  terms.html
Labels: good first issue, SWOC, ADVANCED
